{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--c1ed5b73-7514-4bf1-a147-dd5850bc7f45",
    "created": "2020-05-26T20:30:02.294281Z",
    "modified": "2020-05-26T20:30:02.294281Z",
    "name": "CVE-2019-16226",
    "description": "An issue was discovered in py-lmdb 0.97. mdb_node_del does not validate a memmove in the case of an unexpected node->mn_hi, leading to an invalid write operation. NOTE: this outcome occurs when accessing a data.mdb file supplied by an attacker."
}