{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--1e572eb1-76ff-40b6-b3bd-5d63b3ea6142",
    "created": "2020-05-26T20:29:44.708456Z",
    "modified": "2020-05-26T20:29:44.708456Z",
    "name": "CVE-2018-11499",
    "description": "A use-after-free vulnerability exists in handle_error() in sass_context.cpp in LibSass 3.4.x and 3.5.x through 3.5.4 that could be leveraged to cause a denial of service (application crash) or possibly unspecified other impact."
}