{
    "type": "vulnerability",
    "spec_version": "2.1",
    "id": "vulnerability--90aa5766-7f96-4a7e-94cc-8241c3c00598",
    "created": "2020-05-26T20:29:13.132623Z",
    "modified": "2020-05-26T20:29:13.132623Z",
    "name": "CVE-2015-3206",
    "description": "The checkPassword function in python-kerberos does not authenticate the KDC it attempts to communicate with, which allows remote attackers to cause a denial of service (bad response), or have other unspecified impact by performing a man-in-the-middle attack."
}